package ch.heigvd.sitr.gui;

import javax.swing.*;
import java.awt.*;

public class SettingsWindow {
    private JPanel SettingsPanel;

    private JLabel acronym;
    private JLabel title;
    private JLabel subtitle1;
    private JSeparator separator1;

    private JLabel scenarioLabel;
    private JComboBox scenarioSelector;
    private JSeparator separator2;

    private JSpinner controllerCount1;
    private JSpinner controllerCount2;
    private JSpinner controllerCount3;
    private JSeparator separator3;

    private JLabel subtitle2;
    private JComboBox behaviorSelector;
    private JSeparator sparator4;

    private JButton startButton;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Paramétrage");
        frame.setContentPane(new SettingsWindow().SettingsPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        SpinnerModel model1 = new SpinnerNumberModel(0, 0, 1000, 1);
        SpinnerModel model2 = new SpinnerNumberModel(0, 0, 1000, 1);
        SpinnerModel model3 = new SpinnerNumberModel(0, 0, 1000, 1);
        controllerCount1 = new JSpinner(model1);
        controllerCount2 = new JSpinner(model2);
        controllerCount3 = new JSpinner(model3);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        SettingsPanel = new JPanel();
        SettingsPanel.setLayout(new GridBagLayout());
        SettingsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
        acronym = new JLabel();
        Font acronymFont = this.$$$getFont$$$("Copperplate Gothic Bold", Font.BOLD, 26, acronym.getFont());
        if (acronymFont != null) acronym.setFont(acronymFont);
        acronym.setHorizontalAlignment(0);
        acronym.setHorizontalTextPosition(0);
        acronym.setText("SiTR");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        SettingsPanel.add(acronym, gbc);
        title = new JLabel();
        Font titleFont = this.$$$getFont$$$(null, -1, 18, title.getFont());
        if (titleFont != null) title.setFont(titleFont);
        title.setText("Simulation de Trafic Routier");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.insets = new Insets(0, 50, 0, 50);
        SettingsPanel.add(title, gbc);
        subtitle1 = new JLabel();
        subtitle1.setHorizontalAlignment(0);
        subtitle1.setText("Choix des paramètres du scénario");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(30, 0, 0, 0);
        SettingsPanel.add(subtitle1, gbc);
        separator1 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 0);
        SettingsPanel.add(separator1, gbc);
        scenarioLabel = new JLabel();
        scenarioLabel.setText("Scénario :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 30);
        SettingsPanel.add(scenarioLabel, gbc);
        separator2 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 0);
        SettingsPanel.add(separator2, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.ipadx = 50;
        gbc.insets = new Insets(0, 10, 0, 0);
        SettingsPanel.add(controllerCount2, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.ipadx = 50;
        gbc.insets = new Insets(0, 10, 0, 0);
        SettingsPanel.add(controllerCount3, gbc);
        scenarioSelector = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Croisement");
        defaultComboBoxModel1.addElement("Quartier");
        defaultComboBoxModel1.addElement("Ville");
        defaultComboBoxModel1.addElement("Planete");
        scenarioSelector.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        SettingsPanel.add(scenarioSelector, gbc);
        separator3 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 0);
        SettingsPanel.add(separator3, gbc);
        subtitle2 = new JLabel();
        subtitle2.setHorizontalAlignment(0);
        subtitle2.setHorizontalTextPosition(0);
        subtitle2.setText("Comportement des véhicules lorsqu'ils arrivent à destination :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 10, 0);
        SettingsPanel.add(subtitle2, gbc);
        behaviorSelector = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("retourne au départ");
        defaultComboBoxModel2.addElement("refait le trajet");
        defaultComboBoxModel2.addElement("choisi un nouveau trajet");
        behaviorSelector.setModel(defaultComboBoxModel2);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.gridwidth = 3;
        gbc.ipadx = 50;
        SettingsPanel.add(behaviorSelector, gbc);
        sparator4 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 0);
        SettingsPanel.add(sparator4, gbc);
        startButton = new JButton();
        startButton.setText("Lancer");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.gridwidth = 3;
        gbc.ipadx = 50;
        SettingsPanel.add(startButton, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.ipadx = 50;
        gbc.insets = new Insets(0, 10, 0, 0);
        SettingsPanel.add(controllerCount1, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(11);
        label1.setHorizontalTextPosition(4);
        label1.setText("Agressif :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        SettingsPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Passif :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        SettingsPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Autonome :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        SettingsPanel.add(label3, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return SettingsPanel;
    }

}
