package ch.heigvd.sitr.map.input;

// These imports come from JAXB generated classes
import ch.heigvd.sitr.autogen.opendrive.OpenDRIVE;

import ch.heigvd.sitr.map.RoadNetwork;

import java.io.File;

/**
 * This class is used to parse OpenDrive file (.xodr) and to load the road network
 */
public class OpenDriveHandler {
    /**
     * This method reads the OpenDRIVE format file and create the road network
     *
     * @param roadNetwork   The road network that will be built from the OpenDrive file
     * @param openDriveFile The OpenDrive file with .xodr extension
     */
    public static void loadRoadNetwork(RoadNetwork roadNetwork, File openDriveFile) {
        // Generate data from openDRIVE xml file
        OpenDriveUnmarshaller openDriveUnmarshaller = new OpenDriveUnmarshaller();
        OpenDRIVE openDriveNetwork = openDriveUnmarshaller.load(openDriveFile);

        // From these data, create our road network
        OpenDriveHandler openDriveHandler = new OpenDriveHandler();
        openDriveHandler.create(openDriveNetwork, roadNetwork);
    }

    /**
     * This method creates the road network from the data generated by JAXB
     * @param openDriveNetwork Generated data from the OpenDRIVE XML file
     * @param roadNetwork The road network that will be built from generated data
     */
    private void create(OpenDRIVE openDriveNetwork, RoadNetwork roadNetwork) {

    }
}
